name: Build on demand with artifact

on:
  workflow_dispatch:
  push:    
    tags:        
      - v*

jobs: 

  build-pixel-persistence-for-win10-x64:
    uses: ./.github/workflows/build-pixel-persistence.yml
    with:
      target-os: windows-latest

  build-pixel-persistence-for-linux-x64:
    uses: ./.github/workflows/build-pixel-persistence.yml
    with:
      target-os: ubuntu-latest




